### ISSUE TITLE
使用 laravel 的适配器的时候，数据能写进去，但是检查权限全部是 false

### ISSUE THREAD

**Issue by ljnchn** [php-casbin/webman-permission#1]
![image](https://user-images.githubusercontent.com/6970776/166232580-27abae7a-8544-4d38-9a83-c3d711290e87.png)

调用代码
`Permission::enforce('ljn', 'book', 'read');`
角色的也不行，获取所有角色结果为空，是跟读数据的时候用了缓存有关系吗，需要配置缓存的设置吗？

**Comment by Tinywan** [comment]
配置redis后会自动监控的

**Comment by Jack126** [comment]
遇到同样问题，能详细说说怎么解决的么？

**Comment by ljnchn** [comment]
没解决。。。

**Comment by ljnchn** [comment]
> 遇到同样问题，能详细说说怎么解决的么？

没解决，最后也没找到问题

**Comment by Tinywan** [comment]
最新版本：v1.0.4
