### ISSUE TITLE
addPermissionsForUser可以使用没有加到Permission的静态方法注释里

### ISSUE THREAD

**Issue by lly0414** [php-casbin/webman-permission#15]
能否加上, phpstrom提示方法不存在

**Comment by hsluoyz** [comment]
@Tinywan @leeqvip

**Comment by Tinywan** [comment]
addPermissionForUser 这个方法是有的

**Comment by hsluoyz** [comment]
@Tinywan 那为什么phpstrom会提示方法不存在呢？

**Comment by lly0414** [comment]
应该是因为我是在Permission上静态调用的
```php
Permission::AddPermissionsForUser((string)$role->id, ...$rolePermissions);
```
需要在类的注释上加一下
```php
@method static bool AddPermissionsForUser(string $user, string ...$permission)
```
不过不加也没啥, 就是ide老是提示调用非静态方法, 有点难受 😂

**Comment by lly0414** [comment]
> @lly0414 你能提个PR不？

可以 就是最近在忙 歹稍等两天

**Comment by leeqvip** [comment]
> @Tinywan 那为什么phpstrom会提示方法不存在呢？

PHP 不是强类型语言，和 js 一样，魔法调用，ide追踪不到

**Comment by lly0414** [comment]
@Tinywan @leeqvip  提了pr #16
