### ISSUE TITLE
权限更新或修改时不及时生效！需要webman reload

### ISSUE THREAD

**Issue by mofashi998** [php-casbin/webman-permission#19]
权限更新或修改时不及时生效！

需要 webman reload

"php": ">=7.2",
"workerman/webman-framework": "^1.5.0",
"monolog/monolog": "^2.0",
"webman/console": "^1.2",
"illuminate/database": "^10.29",
"illuminate/pagination": "^10.29",
"illuminate/events": "^10.29",
"symfony/var-dumper": "^6.3",
"illuminate/redis": "^10.29",
"shopwwi/webman-auth": "^1.1",
"casbin/webman-permission": "^1.2"

**Comment by Tinywan** [comment]
你是怎么更新和修改的。直接手动修改数据库？

**Comment by mofashi998** [comment]
使用`deletePermissionForUser `和直接修改数据库都出现这个问题

**Comment by Tinywan** [comment]
我这边没遇到你说的这个问题，可以定位一下，redis订阅哪来打印一下是否有订阅到修改数据

**Comment by lzhlo** [comment]
你解决了吗?好像是数据没有加载缓存到redis.一直在内存里

**Comment by Tinywan** [comment]
不要直接修改数据库，需要通过casbin接口CURD权限
