### ISSUE TITLE
关于在webman中依赖注入配置

### ISSUE THREAD

**Issue by webdick** [php-casbin/webman-permission#20]
是要将
config/container.php 中的
`return new Webman\Container; `
替换成
`$builder = new \DI\ContainerBuilder();
$builder->addDefinitions(config('dependence', []));
$builder->useAutowiring(true);
return $builder->build();`
吗

**Comment by Tinywan** [comment]
是的。按照 https://www.workerman.net/doc/webman/di.html 这个配置即可
