### ISSUE TITLE
有没有结合menu 菜单的demo

### ISSUE THREAD

**Issue by Jack126** [php-casbin/webman-permission#5]
如题。
目前ptype，v0，v1，v2，可结合对应角色 —— 访问路由 —— 请求方式。空余v3，v4，v5是否可延伸出 菜单的方式？

**Comment by leeqvip** [comment]
> 如题。 目前ptype，v0，v1，v2，可结合对应角色 —— 访问路由 —— 请求方式。空余v3，v4，v5是否可延伸出 菜单的方式？

@Jack126 可以的，字段用途可以自定义
