### ISSUE TITLE
第一步必须连接好数据库配置吗？能不能调整成如果配置错误，输出错误而非控制台循环报错

### ISSUE THREAD

**Issue by xianrenqh** [php-casbin/webman-permission#6]
第一步必须连接好数据库配置吗？能不能调整成如果配置错误，输出错误而非控制台循环报错

控制台循环报错，此时webman程序完全无法执行下一步操作，相当于打断点 。
能不能调整成，如果数据库配置错误了，输出错误的同时，webman控制台（cli）不是一直错误，无法执行下一步

**Comment by Tinywan** [comment]
webman 就是基于cli，报错信息就在cli。是必须连接好数据库配置，加载到内存中

**Comment by lyt8384** [comment]
> 第一步必须连接好数据库配置吗？能不能调整成如果配置错误，输出错误而非控制台循环报错
> 
> 控制台循环报错，此时webman程序完全无法执行下一步操作，相当于打断点 。 能不能调整成，如果数据库配置错误了，输出错误的同时，webman控制台（cli）不是一直错误，无法执行下一步

目前已调整成了使用的时候才初始化redis监听器，可避免cli启动报错。

**Comment by Tinywan** [comment]
@lyt8384 nice

**Comment by xianrenqh** [comment]
![image](https://user-images.githubusercontent.com/16522281/225221090-e0facb33-0b94-44d4-9546-775cf8e8379b.png)

升级到 1.1.2版本， 报错这个， 是啥意义 怎么解决

**Comment by lyt8384** [comment]
> 

手动去掉下`config/plugin/casbin/webman-permission/bootstrap.php`文件？ webman的升级好像没有去掉历史文件

**Comment by Tinywan** [comment]
@xianrenqh 可以先删除依赖包。重新安装即可

```
composer remove casbin/webman-permission
```

**Comment by xianrenqh** [comment]
nice
